version: 2
jobs:
  build:
    docker:
      - image: mishguru/circleci:latest
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run: npm ci
      - run: npm run lint
      - run: npm run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: shared
