version: 2
jobs:
    setup:
      docker:
        - image: circleci/node:12
      steps:
        - run:
            name: Setup NPMRC
            command: echo $NPMRC > ~/.npmrc
        - restore_cache:
            key: "v1-git-cache-{{ .Branch }}-{{ .Revision }}"
        - checkout
        - save_cache:
            key: "v1-git-cache-{{ .Branch }}-{{ .Revision }}"
            paths:
              - .git
        - run:
            name: Install dependencies
            command: npm ci
        - save_cache:
            key: "v2-npm-install-cache-{{ checksum \"package.json\" }}"
            paths:
              - ./node_modules
        - save_cache:
            key: "v1-npm-build-cache-{{ .Branch }}-{{ .Revision }}"
            paths:
              - ./dist

    lint:
      docker:
        - image: circleci/node:12
      steps:
        - restore_cache:
            key: "v1-git-cache-{{ .Branch }}-{{ .Revision }}"
        - checkout
        - restore_cache:
            key: "v2-npm-install-cache-{{ checksum \"package.json\" }}"
        - restore_cache:
            key: "v1-npm-build-cache-{{ .Branch }}-{{ .Revision }}"
        - run: npm run lint

    test:
      docker:
        - image: circleci/node:12
      steps:
        - restore_cache:
            key: "v-git-cache-{{ .Branch }}-{{ .Revision }}"
        - checkout
        - restore_cache:
            key: "v2-npm-install-cache-{{ checksum \"package.json\" }}"
        - restore_cache:
            key: "v1-npm-build-cache-{{ .Branch }}-{{ .Revision }}"
        - run: npm run test

workflows:
  version: 2
  build_and_test:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
